env: "local" # local, dev, prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
database:
  user: "postgres"
  password: "Abdrahman"
  dbname: "gowebsocket"
  hostname: "localhost"
  port: 5432