// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserDeleter is an autogenerated mock type for the UserDeleter type
type UserDeleter struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: username, email
func (_m *UserDeleter) DeleteUser(username string, email string) error {
	ret := _m.Called(username, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserDeleter creates a new instance of UserDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDeleter {
	mock := &UserDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
